<a href="https://colab.research.google.com/github/Thannos/Aula10/blob/master/Aula10_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [16]:
a = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
print(a)

[[3 2 4]
 [1 1 2]
 [4 3 2]]


In [0]:
if (np.linalg.det(a) == 0):
    print('Não é possível calcular matriz com determinante igual a 0')

In [20]:
resp1=a[1,0]/a[0,0]
resp2=a[2,0]/a[0,0]
m = np.matrix([[1,0,0],[-resp1,1,0],[-resp2,0,1]])
print('\n',m)


 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


In [21]:
print(m*a)

[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]
