<a href="https://colab.research.google.com/github/Thannos/Aula10/blob/master/Aula10_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [29]:
a = np.matrix([[3,2,4],[1,1,2],[4,3,-2]])
print(a)

[[ 3  2  4]
 [ 1  1  2]
 [ 4  3 -2]]


In [0]:
if (np.linalg.det(a) == 0):
    print('Não é possível calcular matriz com determinante igual a 0')

In [31]:
resp1=a[1,0]/a[0,0]
resp2=a[2,0]/a[0,0]
m = np.matrix([[1,0,0],[-resp1,1,0],[-resp2,0,1]])
print('\n',m)


 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


In [35]:
a1=m*a
print(a1)

[[ 3.00000000e+00  2.00000000e+00  4.00000000e+00]
 [ 0.00000000e+00  3.33333333e-01  6.66666667e-01]
 [ 0.00000000e+00  5.55111512e-17 -8.00000000e+00]]


In [36]:
resp=a1[2,1]/a1[1,1]
m1 = np.matrix([[1,0,0],[0,1,0],[0,-resp,1]])
print(m1)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.66533454e-16  1.00000000e+00]]


In [0]:
def teste(a):
  resp1=a[1,0]/a[0,0]
  resp2=