<a href="https://colab.research.google.com/github/Thannos/Aula10/blob/master/Aula10_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [5]:
a = np.matrix([[3,2,4],[1,1,2],[4,3,2]])
if (np.linalg.det(a) == 0):
    print('Não é possível calcular matriz com determinante igual a 0')
else:
  print(a)

[[3 2 4]
 [1 1 2]
 [4 3 2]]
