<a href="https://colab.research.google.com/github/Thannos/Aula10/blob/master/Aula10(part_II).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def teste(a,n):
  for i in range(1,n):
    p[i]=i
  for k in range(0,n-1):
    pv=a[k,k]
    r=k
    for i in range(k+1,n):
      if (a[i,k]>pv):
        pv=a[i,k]
        r=i
    if(pv==0): return
    if (r!=k):
      aux=p[k]
      p[k]=p[r]
      p[r]=aux
      for j in range(1,n):
        aux=a[k,j]
        a[k,j]=a[r,j]
        a[r,j]=aux
    for i in range(k+1,n):
      m=a[i,k]/a[k,k]
      a[i,k]=m
      for j in range(k+1,n):
        a[i,j]=a[i,j]-m*a[k,j]
  return a

In [77]:
n=3
for i in range(1,n):
  r=p[i]
  c[i]=b[r]
for i in range(i,n):
  soma=0
  for j in range(1,i-1):
    soma+=a[i,j]*y[j]
  y[i]=c[i]-soma
for i in range(1,n,-1):
  soma=0
  for j in range(1,i-1,-1):
    soma+=a[i,j]*x[j]
  x[i]=(y[i]-soma)/a[i,i]

NameError: ignored

In [74]:
p=np.matrix([[0,1,0],[0,0,1],[1,0,0]])#troca as linhas da matrix, sobe tudo
a=np.matrix([[3,1,4],[1,5,9],[2,6,5]])
b=np.matrix([[9],[3],[-2]])
print(a,'\n')
print(p*a,'\n')
print('\n\n------------------------------------------\n\n')
a=teste(a,len(a))#a=U,

[[3 1 4]
 [1 5 9]
 [2 6 5]] 

[[1 5 9]
 [2 6 5]
 [3 1 4]] 



------------------------------------------


