<a href="https://colab.research.google.com/github/Thannos/Aula10/blob/master/para_casa_aula10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [0]:
def decomposicao(a):
  if (np.linalg.det(a) == 0):
    print('Não é possível calcular matriz com determinante igual a 0')
    return
  resp1=a[1,0]/a[0,0]
  resp2=a[2,0]/a[0,0]
  l = np.array([[1,0,0],[resp1,1,0],[resp2,0,1]], dtype='double')
  n = len(a)
  a=l*a
  for k in range(0,n-1):
    for i in range(k+1,n):
        a[i][k] = 0
          
  return l, a

In [0]:
def resolve(m,a1):
  resp=a1[2,1]/a1[1,1]
  m1 = np.matrix([[1,0,0],[0,1,0],[0,resp,1]], dtype='double')
  print(m1)
  b = np.matrix([[1],[2],[3]])
  t = m1*(m*b) 
  print(t)
  return t

In [173]:
a = np.array([[3.,(2.),(4.)], [1.,1.,(2.)], [(4.),(3.),(2.)]])
b = np.array([1.,2.,3.])

print("\nMatriz A:\n",a)
print("\nSolução de X Pelo Linalg:")
resp = np.linalg.solve(a,b)
print(resp)
l, u = decomposicao(a)
print("\nMatriz L: ")
print(l)
print("\nMatriz U: ")
print(u)
y = resolve(l,u)
print("\nLy = b" )
print("Y=" ,y)
print("\nUx = y")
print("X =")
x_solverSystem = resolve(u,y)
print(x_solverSystem)


Matriz A:
 [[3. 2. 4.]
 [1. 1. 2.]
 [4. 3. 2.]]

Solução de X Pelo Linalg:
[-3.  5.  0.]

Matriz L: 
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 0.         1.        ]]

Matriz U: 
[[3. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.        ]
 [2.33333333]
 [4.33333333]]

Ly = b
Y= [[1.        ]
 [2.33333333]
 [4.33333333]]

Ux = y
X =


IndexError: ignored